language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
cache: cargo
script:
  - ./scripts/test.sh
matrix:
  allow_failures:
    - os: windows
    - rust: nightly
  fast_finish: true
