language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
