language: rust
rust:
  # TODO
  - stable
  # - beta
  # - nightly
os:
  # TODO
  # - linux
  # - osx
  - windows
cache: cargo
script:
  - cargo test --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --all-features
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
