[package]
name = "num-format"
version = "0.1.0"
authors = ["Brian Myers <brian.carl.myers@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
failure = "0.1"
libc = "0.2"
lazy_static = "1.2"
apint = { version = "0.2", optional = true }
num-bigint = { version = "0.2", optional = true }
num-rational = { version = "0.2", optional = true }
ramp = { version = "0.5", optional = true }
rug = { version = "1.2", optional = true }

[dev-dependencies]
criterion = "0.2"
separator = "0.3"

[[bench]]
name = "benchmark"
harness = false
