[package]
name = "num-format-dev"
version = "0.1.0"
authors = ["Brian Myers <brian.carl.myers@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
itertools = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
